FROM registry.access.redhat.com/ubi8/ubi-minimal
RUN microdnf install wget tar gzip
RUN wget https://go.dev/dl/go1.19.4.linux-amd64.tar.gz
RUN sha256sum go1.19.4.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go*.linux-amd64.tar.gz
RUN rm -rf go1.19.4.linux-amd64.tar.gz
ADD arrowbuilder .
WORKDIR /arrowbuilder
RUN /usr/local/go/bin/go mod tidy
